server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 单机版
      #defaultZone: http://eureka7001.com:7001/eureka
      # 集群版 设置与 Eureka Server 交互的地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true    #访问路径可以看见IP地址
    #以下是在设置关闭自我保护时的设置
    #Eureka客户端向服务端发送心跳的时间间隔 （单位秒，默认30秒）
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90秒），超时将剔除服务
    #lease-expiration-duration-in-seconds: 30
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lyh.springcloud.entities  # 所有Entity 别名类所在包